services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ~/.data/mongodb/data/db:/data/db
      - ~/.data/mongodb/data/util:/data/util

  satifile:
    image: satifile:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      tags:
        - "satifile:latest"
    restart: always
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ~/uploads:/app/server/uploads
